execute pathogen#infect()

""Vim Settings""
syntax on
filetype plugin indent on
set nu
set expandtab
set tabstop=4
autocmd BufWritePre * :%s/\s\+$//e

""Colors""
set t_Co=256
colorscheme molokai
let g:molokai_original = 1
let g:rehash256 = 1

""Syntastic""
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_python_flake8_args='--ignore=E221,E501'
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

""Airline""
set laststatus=2
let g:airline#extensions#tabline#enabled = 1
